version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/ronakbanka/git-issue-count
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
      - run:
        name: Setup CF CLI
        command: |
          curl -v -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&source=github'
          sudo dpkg -i cf-cli_amd64.deb
          cf -v
          cf api https://api.run.pivotal.io  # alternately target your private Cloud Foundry deployment
          cf auth "$CF_USER" "$CF_PASSWORD"
          cf target -o "$CF_ORG" -s "$CF_SPACE"
