version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/ronakbanka/git-issue-count
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
      - run:
          name: Setup CF CLI
          command: |
            curl -v -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&source=github'
            sudo dpkg -i cf-cli_amd64.deb
            cf -v
            cf api https://api.run.pivotal.io  # alternately target your private Cloud Foundry deployment
            cf auth "$CF_USER" "$CF_PASSWORD"
            cf target -o "$CF_ORG" -s "$CF_SPACE"
      - run:
          name: CF Deploy
          command: |
            cf push --no-start git-issue-count
            # Pass CircleCI variables to Cloud Foundry (optional)
            cf set-env git-issue-count circle_build_num ${CIRCLE_BUILD_NUM}
            cf set-env git-issue-count circle_commit ${CIRCLE_SHA1}
            cf set-env git-issue-count circle_workflow_guid ${CIRCLE_WORKFLOW_ID}
            cf set-env git-issue-count circle_user ${CIRCLE_PROJECT_USERNAME}
            cf set-env git-issue-count circle_repo ${CIRCLE_PROJECT_REPONAME}
            # Start the application
            cf start git-issue-count
